@startuml
participant User
participant App
participant Database


User -> App : Add customer info and comfirm cart
App -> Database :  Check if Customer already in database

alt Known customer

Database -> App : Customer already in Database

else Unknown customer

Database -> App : Customer not in Database
App->Database : Create customer in Database

end

App->Database: Get customer number
Database -> App: return customer number
App->Database:Create invoice
App->Database:Create invoice details

App->App: Clears cart and customer info

@enduml