@startuml
start
repeat
partition "**process** Init" {
    
fork
  :get stock from DB;
fork again
  :get production
 from DB;
end merge
    :Display stok state;
}
switch ()
case ( [Add Part] )
  :uptdate part table ;
case ( [Order Part] ) 
  :uptdate orderder part table;
case ( [Use Part] )
  :updtate part table;
case ( [Display ordered part] )
if (part receveid) is ([Yes]) then
:update ordered part table;
else ([no])
endif
endswitch
@enduml
