@startuml Planning
start
:get orders;
:check stock;
if (stock) is (not enough) then
	:order minimum stock;
else (enough)
endif
if (parts) is (enough) then
	:Add order to prod planning;
else (not enough)
	:order missing parts;
endif
stop
@enduml