@startuml Sale
start
:get planning;
:start prod;
:get parts list;
repeat :ask stock;
:get parts;
:update stock;
backward :discard part;
repeat while (parts) is (faulty) not (valid)
:build bike;
:confirm build and update planning;
stop
@enduml
