@startuml Prototype

left to right direction

:Representative:
:Production_manager:
:Mechanic:

Package System{
	left to right direction
	Package Sales{
		(Show the catalog) as (uc1)
		(Get a shipping date) as (uc6)
		(Enter a new order) as (uc5)
	}

	Package Production{
		(See prod plannig) as (uc2)
		(See stock) as (uc3)
		(Confirm end of school) as (uc4)
		(Start production) as (uc7)
		(Plan  production) as (uc8)
		(Manage stock) as (uc9)
	}
}

uc3 <-- Production_manager
uc7 <-- Production_manager
uc8 <-- Production_manager
uc9 <-- Production_manager
uc2 <-- Mechanic 
uc3 <-- Mechanic 
uc4 <-- Mechanic 
Representative --> uc1
Representative --> uc5
Representative --> uc6

Sales -[hidden]-> Production

@enduml