@startuml Sale
start
:show catalog;
if () is (Interested) then
:choose models and quantity;
:get shipping date estimate;
if () is (Cancelled) then
stop
else (Validate)
:get contact details;
:save order;
stop
endif
else (Not interested)
stop
endif
@enduml
