
@startuml
participant Seller
participant Interface
participant Db
Interface ->Db: get information
Seller-> Interface: press on model

Interface->Seller: show information

Seller-> Interface: add to cart
Seller-> Interface: encode customer data

Seller-> Interface: confirm cart
Interface -> Db: save customer data
Interface -> Db: add command

@enduml